<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0yBlNsh\Neuron_BuildingBlocks_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0yBlNsh/Neuron_BuildingBlocks_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0yBlNsh.legacy');

    return;
}

if (!\class_exists(Neuron_BuildingBlocks_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0yBlNsh\Neuron_BuildingBlocks_KernelDevDebugContainer::class, Neuron_BuildingBlocks_KernelDevDebugContainer::class, false);
}

return new \Container0yBlNsh\Neuron_BuildingBlocks_KernelDevDebugContainer([
    'container.build_hash' => '0yBlNsh',
    'container.build_id' => '04bb485e',
    'container.build_time' => 1682066751,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0yBlNsh');
