name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  static-analysis:
    name: Static Analysis
    
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHP CS
      run: composer run-script php-cs

    - name: PHP Stan
      run: composer run-script php-stan
      
  tests:
    name: Tests

    needs: static-analysis

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Unit tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Code coverage badge generation
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: ./coverage.xml
          coverage_badge_path: output/coverage.svg
          push_badge: false

      - name: Code coverage badge push
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
